export const users = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    password: "password123",
    phoneNumber: "123-456-7890",
    status: "ACTIVE",
    role: "ADMIN",
    gender: "MALE",
    avatar: "avatar1.png",
    enrolledCourses: ["course1", "course2"],
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    password: "password123",
    phoneNumber: "098-765-4321",
    status: "INACTIVE",
    role: "STUDENT",
    gender: "FEMALE",
    avatar: "avatar2.png",
    enrolledCourses: ["course3"],
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alicejohnson@example.com",
    password: "password123",
    phoneNumber: "234-567-8901",
    status: "ACTIVE",
    role: "STUDENT",
    gender: "FEMALE",
    avatar: "avatar3.png",
    enrolledCourses: ["course1", "course4"],
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    email: "bobbrown@example.com",
    password: "password123",
    phoneNumber: "345-678-9012",
    status: "SUSPENDED",
    role: "ADMIN",
    gender: "MALE",
    avatar: "avatar4.png",
    enrolledCourses: [],
  },
  {
    firstName: "Charlie",
    lastName: "Davis",
    email: "charliedavis@example.com",
    password: "password123",
    phoneNumber: "456-789-0123",
    status: "ACTIVE",
    role: "STUDENT",
    gender: "MALE",
    avatar: "avatar5.png",
    enrolledCourses: ["course2"],
  },
  {
    firstName: "Diana",
    lastName: "Evans",
    email: "dianaevans@example.com",
    password: "password123",
    phoneNumber: "567-890-1234",
    status: "ACTIVE",
    role: "STUDENT",
    gender: "FEMALE",
    avatar: "avatar6.png",
    enrolledCourses: ["course1", "course3"],
  },
  {
    firstName: "Eve",
    lastName: "Foster",
    email: "evefoster@example.com",
    password: "password123",
    phoneNumber: "678-901-2345",
    status: "INACTIVE",
    role: "ADMIN",
    gender: "FEMALE",
    avatar: "avatar7.png",
    enrolledCourses: ["course4"],
  },
  {
    firstName: "Frank",
    lastName: "Green",
    email: "frankgreen@example.com",
    password: "password123",
    phoneNumber: "789-012-3456",
    status: "SUSPENDED",
    role: "STUDENT",
    gender: "MALE",
    avatar: "avatar8.png",
    enrolledCourses: [],
  },
  {
    firstName: "Grace",
    lastName: "Harris",
    email: "graceharris@example.com",
    password: "password123",
    phoneNumber: "890-123-4567",
    status: "ACTIVE",
    role: "STUDENT",
    gender: "FEMALE",
    avatar: "avatar9.png",
    enrolledCourses: ["course2", "course4"],
  },
  {
    firstName: "Henry",
    lastName: "Iverson",
    email: "henryiverson@example.com",
    password: "password123",
    phoneNumber: "901-234-5678",
    status: "INACTIVE",
    role: "ADMIN",
    gender: "MALE",
    avatar: "avatar10.png",
    enrolledCourses: ["course3"],
  },
];

export const courses = [
  {
    _id: 1,
    title: "Amazon",
    price: "12000",
    coverImage:
      "https://res.cloudinary.com/zenbusiness/image/upload/v1670445040/logaster/logaster-2020-03-amazon-gif-logo.jpg",
  },
  {
    _id: 2,
    title: "Shopify",
    price: "19000",
    coverImage: "https://img.supdropshipping.com/wp-content/uploads/2023/10/What-Is-Shopify-2.jpg",
  },
  {
    _id: 3,
    title: "Fiverr",
    price: "14000",
    coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1wiMzUlVk9c5moWGd5qVJlEIewU1xk51DJw&s",
  },
  {
    _id: 4,
    title: "Trading",
    price: "18000",
    coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTto6IjeA7HhikyRuKkq0S3vSmK0Tp4oXrrHg&s",
  },
  {
    _id: 5,
    title: "Freelancing",
    price: "19000",
    coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgITwdVrnn0EcVsY3sFhDF11DCi_xc26y4jQ&s",
  },
  {
    _id: 6,
    title: "Fiverr GiG",
    price: "9000",
    coverImage:
      "https://www.meersworld.net/wp-content/uploads/How-to-sign-up-for-Fiverr-Seller-account-and-create-your-first-Gig.webp",
  },
];

export const courses2 = [
  {
    id: "1",
    title: "React Basics",
    description:
      "Learn the fundamentals of React, including components, state, and props. Learn the fundamentals of React, including components, state, and props. Learn the fundamentals and props.Learn the fundamentals of React, including components, state, and props.",
    introVideoUrl: "https://www.youtube.com/watch?v=BHy9kXR1n-c",
    lectures: [
      { title: "Introduction to React", link: "https://www.youtube.com/watch?v=KUpwupYj_tY" },
      { title: "React Components", link: "https://www.youtube.com/watch?v=8sLS2knUa6Y" },
      { title: "State and Props", link: "https://www.youtube.com/watch?v=LK7-_dgAVQE" },
    ],
  },
  {
    id: "2",
    title: "Advanced React",
    description: "Dive deeper into React with hooks, context, and advanced patterns.",
    introVideoUrl: "https://www.youtube.com/watch?v=example2",
    lectures: [
      { title: "Hooks in React", link: "https://www.youtube.com/watch?v=lecture4" },
      { title: "Context API", link: "https://www.youtube.com/watch?v=lecture5" },
      { title: "React Patterns", link: "https://www.youtube.com/watch?v=lecture6" },
    ],
  },
  // More courses...
];
